# Generated by Django 4.0.4 on 2022-05-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Memory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.PositiveIntegerField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("place", models.TextField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("uid", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("avatar", models.TextField()),
            ],
        ),
    ]
