# Generated by Django 4.0.4 on 2022-05-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_memory_zoom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('uid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=30)),
            ],
        ),
    ]
